# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdd2818302c1c6653cac959ac07c504327141c3032dc6df625ea0f7d11877ee299d52b36d18043af45b85ccb534bd4d021255e10b80b90b3cae086c11599bba9

test:
  secret_key_base: c7cbd5d08bcb90ee8ff0b6f0f177bc10f269adcf4da83f83038f74f1cf2da24084a537c933963f61b7d1c8d6fad42384303b8bfa1ad3e1c0132ab4e7688f75e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
